### ISSUE TITLE
just notice that your normal in shader is wrong

### ISSUE THREAD

**Issue by SnowWindSaveYou** [mlavik1/UnityVolumeRendering#100]
the volume is not like the mesh which has two side faces so the normal can be negative, 
while the normal of volume is always be positive to the view direction, 
so when you calculate the light you need to first calculate the dot production of view direction with normal, then reverse the normal if it is negative.
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/31602852/172333341-0576d5b1-21d4-4ad3-a87c-9806762d422b.png">
Left is your current approach, and the right is fixed result.
```hlsl
            // Performs lighting calculations, and returns a modified colour.
            float3 calculateLighting(float3 col, float3 normal, float3 lightDir, float3 eyeDir, float specularIntensity)
            {
                 if(dot(normal,eyeDir)<0)normal = -normal;
                float ndotl = max(lerp(0.0f, 1.5f, dot(normal, lightDir)), 0.5f); // modified, to avoid volume becoming too dark
                float3 diffuse = ndotl * col;
                float3 v = eyeDir;
                float3 r = normalize(reflect(-lightDir, normal));
                float rdotv = max( dot( r, v ), 0.0 );
                float3 specular = pow(rdotv, 32.0f) * float3(1.0f, 1.0f, 1.0f) * specularIntensity;
                return diffuse + specular;
            }
```

**Comment by mlavik1** [comment]
Hi! Thanks for the feedback :)

Maybe I misunderstood you slightly, but I think it should be right to assume that the normal can be negative?`
I use the gradient magnitude ( = the direction of change in density values) to calculate the normal, and that can point both towards and away from the light.
So for example: If you're viewing the back side of a skull, while the light source is on the opposite side, then the skull should appear dark. At least for isosurface rendering mode - but maybe not in direct volume rendering mode? 🤔 

However, that's all hypothetical, since the light direction has been hard coded to be equal to the view direction 😅 
I will take a look at that next. I could probably just modify the normal and use Unity's built-in lighting calculations instead, Or at least use the Unity main light.

**Comment by SnowWindSaveYou** [comment]
i'm sorry for didn't reply that long time, 
actually i mean that normal can be any direction but always toward viewer.
for example you can viewing a long form both outside and inside.
when you viewing from outside, the normal of the surface of lung is from inside to outside.
but if you viewing it from inside the normal should be opposite,  and if still use same normal as  viewing from outside, you would see that lung become dark anyway.

**Comment by SnowWindSaveYou** [comment]
![jumpbrickpreview](https://user-images.githubusercontent.com/31602852/187677899-3bd60515-616b-4d97-9660-3c77cc9c8d69.png)
made some optimize on bounding box of ray-cast, but this is too large change ...

**Comment by mlavik1** [comment]
@SnowWindSaveYou Hmm.. I think you're right!
If the light source is right above the dataset, and we view it form below, it should appear dark. But currently we get too much diffuse lighting in that case. Inverting the normals (when dot(n,l) is negative) fixes that.
I'll make a pull request for this, and see if I can also fix some other lighting related issues while I'm at it!

Thanks!

**Comment by mlavik1** [comment]
Ok, I've pushed a fix and made a PR.
Does this seem right? https://github.com/mlavik1/UnityVolumeRendering/pull/107/files#diff-547394143ada2254be67b4ef5c602882bf0c188d2a720a4860bb658f366d8505R197

It's basically the same as:
```glsl
if(dot(normal, eyeDir) < 0.0)
   normal *= -1.0
```
But possibly faster.

I'm also adding support for using the main light, rather than the camera view vector, as light direction. Will add that to the settings window.

**Comment by mlavik1** [comment]
I also realised that parts of the dataset where the gradient magnitude is near zero, using the graident vector as a normal doesn't work so well. This article suggests some approaches to deal with it: https://developer.openinventor.com/UserGuides/Oiv10/Users_Guide/VolumeViz/Volume_Rendering/Volume_rendering_effects.html
I'll make another task for that. 
Anyway, inverting the normal as you suggested works quite well, so I'll merge my PR now. Thanks again!
