### ISSUE TITLE
Doesn't look 3D in VR (Oculus Quest 2)

### ISSUE THREAD

**Issue by bittu97** [mlavik1/UnityVolumeRendering#136]
The model doesn't look 3D if we build it in Oculus or in VR.

**Comment by bittu97** [comment]
> The model doesn't look 3D if we build it in Oculus or in VR.

Solution (By Matias Lavik): Just change stereo render mode to multi-pas, in Unity. This works fine.

**Comment by mlavik1** [comment]
Thanks for adding it here as well :) I'll keep the task open for now, since the actual issue has not been solved (should work without multi-pass).

**Comment by karstennoe** [comment]
Hi Matias. Have you fixed the shaders for single pass stereo? Otherwise I have made the changes locally in my own repo. It works (tested on Varjo Aero). Might as well be put back in the main repo?

**Comment by mlavik1** [comment]
Hi @karstennoe , thanks for asking!
I'm no longer working in the VR industry, and don't have a headset. My friend will borrow me one after new year, so then I should finally be able to look at some of the VR related issues.
So no, I have not been able to fix this. Feel free to make a PR! That would be very much appreciated!

**Comment by karstennoe** [comment]
Hi again. 

What I have done is simply to enable stereo support in the shaders:

![2022-12-28 12_13_48-Plane views now also support VR (f3a3443f) · Commits · Karsten Østergaard Noe _ ](https://user-images.githubusercontent.com/46138921/209804039-9e105d82-8c39-4375-869b-9b8a5d664396.png)
![2022-12-28 12_15_04-Stereo Volume Rendering now works!!! (de56eac1) · Commits · Karsten Østergaard N](https://user-images.githubusercontent.com/46138921/209804042-de09bf6d-465c-4ca8-9031-77bdb8f2f869.png)

However, I might have jumped the gun a bit on this, as I experience some issues with composition of volume rendering and polygon mesh rendering. When running e.g. a VR glove through the volume it is clear that left and right eye views don't aggree on where the volume object and mesh object intersect - in my view this indicates that the two rendering modes don't completely agree on model, view and/or projection on at least one of the eyes (the effect is too large to merely be numerical issues with depth reporting in the volume rendering IMO). 

In VR this can be quite disturbing - especially when getting close to the object, so I better investigate further before creating a PR.

**Comment by mlavik1** [comment]
Thanks for sharing!
I'll see if I can also look into it a bit when I get a VR headset.

Do you notice this issue when using multi-pass rendering also?

**Comment by karstennoe** [comment]
Hi again

Thanks for responding.

> Do you notice this issue when using multi-pass rendering also?

After fighting all morning with getting the Varjo base software working again after it mysteriously refused to work (happens once in a while for me), I finally managed to test that out. And it does indeed seem like the issue is **not present** when using the multi-pass rendering. However the rendering frame rate is also _significantly_ lower in multi-pass mode than single-pass instanced mode.

I took the screen shot attached (or rather I had to yell for someone to come and click the screenshot button ;-) ). It looks to me like the volume renderings are displaced with respect to each other with what could be the eye spacing. 

![varjo_screenshot_2023-01-02_15-11-16-394](https://user-images.githubusercontent.com/46138921/210244234-6902012d-7dac-44b8-969b-0da1a98636b5.png)

**Comment by karstennoe** [comment]
Hi again!

Good news! I managed to fix it. 

I had missed adding the magic spell "UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(i)" in the fragment shader. I think what happened was that the  built in function **ObjSpaceViewDir** was incorrectly computing object space view directions for the second eye as if has been rendered from the first eye. 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/46138921/210253240-f2175151-1a0f-472e-be3b-21d5f1c52797.png">

Sorry for wasting your time thinking over this!

**Comment by mlavik1** [comment]
Nice, so it's working fine with that change?
Thanks a lot for looking into this :) 

I made a PR with your suggested changes. Would you mind trying it out for me?
See #148 148

**Comment by mlavik1** [comment]
Really glad to hear that! :) 

Hmm.. yes that could be! What kind of issues do you end up seeing when using motion smoothing?
And thanks! Please let me know when you've had time to test the PR, so I can merge it.

Hmm.. good question! Currently, my recommended ways to use it would be to:
A. Add it as a git submodule (I personally like this way).
B. Use the [unity package builds](https://github.com/mlavik1/UnityVolumeRendering/releases)
C. Use the [Asset store version](https://assetstore.unity.com/packages/vfx/shaders/easy-volume-renderer-192890).
It's a pain to update the asset store version though (have finally set up automatic build scripts for that now though!).

I don't have much experience with "real" unity packages though (using `package.json`), so I'll need to read up on that a bit first, but that's probably something I should do :) 
There's one thing I'm not sure about though.. I'd like people to be able to simply pull my repo, open it as a project and run the sample scene. Is there a way to achieve both?
I suppose I could keep the repository as a project (like now) and place the actual package in a sub-folder, and have the outer project reference it (as a local package). But I suppose "Add package form Git URL" wouldn't work then, since the package is placed in a subfolder of my repo.. Am I missing something maybe? :sweat_smile:

**Comment by karstennoe** [comment]
Hi Matias

The PR branch works in single pass instanced mode on both the OpenVR shipped with SteamVR, OpenXR (on Arjo) as well as the Arjo Mode. So I think it is save to merge.

Here is an image of the artifacts I mentioned: 
 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/46138921/211145221-d5bcd7d2-474f-45fe-8d97-76bfddb759c3.png">

They can only be seen when moving the HMD in Varjo mode or OpenXR with depth output enabled (so that varjo can do motion compensation in its compositor). So I am quite convinced it is an inherent issue in the motion compensation approach (for transparent objects) rather than something to be handled in your repo. Whether or not the foveated rendering also leads to issues is harder for me to determine.

A note though: In this case OpenXR has a significantly lower performance than the two other modes (and OpenVR has a lower resolution than Varjo). So if somebody complains about performance in OpenXR mode, perhaps suggest to try OpenVR?

**Comment by karstennoe** [comment]
Sure!

I have no other headsets to test on, so I couldn't be sure! It may only be a Varjo thing. It sounds like more advanced stuff is happening in varjos OpenXR backend than in the OpenVR one, and indeed the difference may simply be down to the OpenXR supporting a higher resolution than OpenVR on Varjo - and thus lower frame rates. However as you know getting under a certain performance threshold in VR can be quite nauseating!

By the way, I ended up taking the git submodule approach - I think that works fine!

**Comment by mlavik1** [comment]
Hmm, yes that could be!
I'll probably find out on Thursday then, if I get my VR headset :D  (a Quest)

By the way, if you're struggling with low framerates, have you tried using [DLSS](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@12.0/manual/deep-learning-super-sampling-in-hdrp.html)? I've never used it with this project, but I can imagine it will give a nice performance boost since the bottleneck without doubt is the pixel shader. It requires HDRP though - I'm not sure if you'll need to modify the shaders to get them to work (with VR), or if the auto-upgrade tool fixes it.

Ok, nice to hear!
