### ISSUE TITLE
DICOM datasets up-side-down

### ISSUE THREAD

**Issue by mlavik1** [mlavik1/UnityVolumeRendering#185]
DICOM datasets consistently spawn up-side-down:

I believe it has always been like this. Before #170 they were also mirrrored. Now the coordinate system should be correct, except the rotation is wrong.

![image](https://user-images.githubusercontent.com/6906872/235640423-91d2e814-2b0b-4129-a17a-c9ff95d2b52a.png)

**Comment by SitronX** [comment]
Hi @mlavik1 

>I assume your DICOM datasets also spawn up-side-down? (just not mirrored anymore 😁 )

Yes all my dicom, but also NRRD are upside down (i guess Niftis are also upside down due to SimpleITK?). 

>Though, we probably don't want the head pointing downwards, so I guess it should be fine to change this? 

Ye i guess it is fine. I dont know how people use this library, but i guess they do not update their clone or whatever everytime they launch their app. Myself, I downloaded latest version of your library to my project somewhere in January and only manually updated some crucial things since then.

If somebody did use it in their app with ability to update this library automatically i would be actually curious how they have done it. I guess this could be maybe done with Unity Asset store when trying to update the asset thru package manager? Or could the clone of this library be stored also in new Unity project? Would it update correctly by pulling latest commits? Hmm. But this would forbid you to do any changes to library itself due to merge conflicts with updates in the future, so i guess downloading latest version and updating manually is the only option if you wanted to make changes inside it, right? :D

**Comment by mlavik1** [comment]
> Yes all my dicom, but also NRRD are upside down (i guess Niftis are also upside down due to SimpleITK?).

Ok, good to hear it's consistent at least :) And yes, Niftis are also affected by that, unless you disable SimpleITK (there's another Nifti importer too haha).

> Ye i guess it is fine. I dont know how people use this library, but i guess they do not update their clone or whatever everytime they launch their app. Myself, I downloaded latest version of your library to my project somewhere in January and only manually updated some crucial things since then.

Hmm yes. If someone wants a very stable experience, I would hope they either use the Asset Store version or one of the packaged releases. I'll make sure to add a note about the coordinate system changes in the release notes both places!

Most people (except the very technical ones who are developing their own software using this plugin) seem to import datasets through the editor, and then they probably rotate it manually there. Either way, I guess we don't want the datasets to be up-side-down forever 😅 

If somebody did use it in their app with ability to update this library automatically i would be actually curious how they have done it. I guess this could be maybe done with Unity Asset store when trying to update the asset thru Unity package manager? Or could the clone of this library be stored also in new Unity project? Would it update correctly by pulling latest commits? Hmm. But this would forbid you to do any changes to library itself due to merge conflicts with updates in the future, so i guess downloading latest version and updating manually is the only option if you wanted to make changes inside it, right? :D

> Hmm, good question! I would probably recommend:
- If they want to use it as it is: Download .unitypackage from release and push the whole plugin source code to your project. (or use asset store version).
- If they plan to modify it: Fork the repository, and add the fork as a git submodule.

Or what do you think?
I should probably write about these things in the readme 😁

**Comment by SitronX** [comment]
Hi @mlavik1 
Ohh yes, git submodules are probably ideal for that. Didnt know about them until now, thanks for this info. Still relatively new with git, i should probably spent some time researching all its options :D
