### ISSUE TITLE
Option to reduce the brightness of the volume object.

### ISSUE THREAD

**Issue by Meruja** [mlavik1/UnityVolumeRendering#218]
I'm searching for an option to decrease the object's brightness. I've experimented with the following solutions, but they aren't providing the desired results:
1. Adjusting the intensity or direction of the directional light within the scene.
2. Setting the opacity value to 0 for lower intensity values.

Is there a more effective method to achieve this?

**Comment by mlavik1** [comment]
Hi @Meruja !

Rather than modifying the opacity values, I'd suggest adjusting the colours in the transfer functions. For example, if your TF is using red and green colour, switch to dark red and dark green.
Also, changing the scene's background colour to black (currently it's light blue) can help a bit, since semi-transparent parts of the volume will mix with the background. It's quite common to use a black background - but I suppose it's a matter of preference. It might make the volume looks a bit darker, and make contrasts more apparent.
Example: 
![image](https://github.com/mlavik1/UnityVolumeRendering/assets/6906872/1774ce47-246e-450b-8d77-0a988f2fd88a)
