### ISSUE TITLE
Import Dicom without Slice Location

### ISSUE THREAD

**Issue by ffreller** [mlavik1/UnityVolumeRendering#25]
Hello Mr. Lavik, thank you for sharing your code.
I am currently dealing with Dicom files that do not have the Slice Location tag.
I've managed to fill this tag with information that is coherent but not identical to Slice Location, according to the formula shared in this thread https://groups.google.com/g/comp.protocols.dicom/c/F3RKlfBVkJ4
As I undestand, your code uses this tag to sort the slices in the dataset. When using the method shared above, the order of the slices is maintained --and this fact leads me to assume it would enable a correct sorting of the slices.
When I run the DICOMImporter, though, it does not generate the expected image. Do you have any suggestions on how to deal with it?

**Comment by mlavik1** [comment]
Hello!
So you dataset lacks the "Slice location" tag, but you have been able to fill it yourself (using the formula in that thread), right?
First of all: How does the result look? Is the shape wrong, or does the whole dataset become unrecognizable? (noise). If you have a picture, that would be useful :) 
The default transfer function might not look good on all datasets, so I would recommend testing with "maximum intensity projection" and "isosurface" render modes as well, just to make sure it's not an issue with the transfer function.

Also, have you been able to verify that the slice locations are indeed correct in the modified version of the dataset? For example, you could try importing it in another 3D dicom viewer (one that does 3D volume rendering), such as ImageVis3D (https://www.sci.utah.edu/cibc-software/imagevis3d.html). If it works there, then I guess it's a bug (or a missing feature) in my DICOM importer.

If you are allowed to share the datasets I'd be happy to look at it when I have time! If not, I'll still try to help you with what I can.

Oh and I have a question for you: is it common for DICOM files to not have a "slice location" tag but only an orientation (direction cosine) tag? I'm not that experienced with the DICOM format so I don't know what is common practice there, but if that's the case I could probably look into implementing something similar to the method discussed in the thread you shared. That would have to wait a few weeks though, since we're expecting a child soon and I'll probably be busy

**Comment by mlavik1** [comment]
Oh, and another thing: Are the slices uniformly distributed? (is the distance between each slice the same?). The DICOM importer assumes that this is the case. That was the case for the DICOM files I tested with, but I'm not sure if that is always the case? I think that should be fairly simple to fix. However, if that's the issue I think the imported dataset should still be recognisable - only look a bit distorted. But I'm curious about how it looks in ImageVis3D. If it looks correct there but not "Unity Volume Rendering", then I guess that could be the issue.

**Comment by ffreller** [comment]
First of all, thank you for answering in such a short time
**> So your dataset lacks the "Slice location" tag, but you have been able to fill it yourself (using the formula in that thread), right?**
Yes, that's it.

**>First of all: How does the result look? Is the shape wrong, or does the whole dataset become unrecognizable? (noise). If you have a picture, that would be useful :)
The default transfer function might not look good on all datasets, so I would recommend testing with "maximum intensity projection" and "isosurface" render modes as well, just to make sure it's not an issue with the transfer function.**
Here is an image of the result. I have already tried modifying the tranfer function. It did not work
![image](https://user-images.githubusercontent.com/32555469/95389123-c0bd1d00-08c9-11eb-85da-c4fc880f7649.png)

**>Also, have you been able to verify that the slice locations are indeed correct in the modified version of the dataset? For example, you could try importing it in another 3D dicom viewer (one that does 3D volume rendering), such as ImageVis3D (https://www.sci.utah.edu/cibc-software/imagevis3d.html). If it works there, then I guess it's a bug (or a missing feature) in my DICOM importer.**
Yes, it did work on ImageVis3d. Here's an image
![image](https://user-images.githubusercontent.com/32555469/95389762-af284500-08ca-11eb-8d01-6e457bd23d62.png)

**>If you are allowed to share the datasets I'd be happy to look at it when I have time! If not, I'll still try to help you with what I can.**
Yes, I can share it with you. Just give me some hours to anonymize the dataset. And it would be better if I could send it to you privately instead of posting it here. Is it possible?

**>Oh and I have a question for you: is it common for DICOM files to not have a "slice location" tag but only an orientation (direction cosine) tag? I'm not that experienced with the DICOM format so I don't know what is common practice there, but if that's the case I could probably look into implementing something similar to the method discussed in the thread you shared. That would have to wait a few weeks though, since we're expecting a child soon and I'll probably be busy with that the first weeks**
Yes, it's very common, at least in Brazil. But I've read online that it is also common elsewhere. According to what I've read, this tag is not very reliable. No worries about the time, good luck to you and your wife and thank you for your help.

**>Oh, and another thing: Are the slices uniformly distributed? (is the distance between each slice the same?). The DICOM importer assumes that this is the case. That was the case for the DICOM files I tested with, but I'm not sure if that is always the case? I think that should be fairly simple to fix. However, if that's the issue I think the imported dataset should still be recognisable - only look a bit distorted. But I'm curious about how it looks in ImageVis3D. If it looks correct there but not "Unity Volume Rendering", then I guess that could be the issue.**
The distances are not the same, but are very similar. In one example, it varies between 0.8000000000000682 and
0.7999999999999545. Do you think that this is the problem?

**Comment by mlavik1** [comment]
Thanks for the feedback!
Hmm.. looks like it's a bug on my side then.
You can send the dataset to: matias.lavik@hotmail.com. I don't use the e-mail that often, so just write a message here when you have sent it :) 

Ok, I see. Thanks for the info!
I'll add a task to automatically calculate slice locations then.

And if the variation in distance between the slices is that small, then I don't think that is the issue. Though, it's still something I need to fix at some point.

**Comment by ffreller** [comment]
I'm, sorry, I was mistaken about the variance of the distances. Here are all the unique values.
{0.8000000000000682, 0.7999999999999545, 0.8000000000000114, 0.8009999999999309, 0.8010000000000446, 0.8009999999999877, 0.799999999999983, 0.8010000000000161, 0.7999999999999972, 0.8010000000000019, 0.7998999999999938, 0.8000999999999863, 0.8000500000000006, 0.8000499999999988, 0.8000999999999934, 0.8000999999999969, 0.8000999999999987, 0.8001000000000005, 0.8000799999999995, 0.8000499999999997, 0.8000400000000001, 0.8000484999999999, 0.8000449999999999, 0.8000499999999999, 0.8000500000000001, 0.800048, 0.7999999999999989, 0.8000000000000007, 0.8000000000000043}

I've just sent you the link. Let me know after you've downloaded so I can delete it.

**Comment by mlavik1** [comment]
Hi! I have downloaded the dataset, so you can remove it now.
Apparently the issue was that the pixel data was in int16 format, while my importer only worked with 8-bit formats.
I will do a proper fix for this later (need to read a bit more about pixel data formats in DICOM first), but I have pushed a hack-fix that you can use to import your dataset.
I pushed it to the branch: issue25-dicom-pixelformat

Please "git checkout issue25-dicom-pixelformat" and try importing again. That should work 😄 

Also, the dataset is very large so you need a lot of RAM if you want to use "isosurface rendering" or 2D TFs, because those need to generate a gradient texture. I'll work on improving that later. I should probably add some limit to the detail of the gradient texture or something. But for now this fix should at least allow you to import your dataset. Please let me know if you encounter any other issues!

**Comment by ffreller** [comment]
It worked! Thank you.

**Comment by mlavik1** [comment]
Good to hear :)  I'll merge it into master after I have done a more proper fix (for handling other formats as well).
Thanks a lot for the bug report 👍

**Comment by mlavik1** [comment]
Both issues should be fixed now :)
