### ISSUE TITLE
Custom transfer function issue with 'texture' variable in an inherited class from TransferFunction.cs

### ISSUE THREAD

**Issue by kvijaykiran** [mlavik1/UnityVolumeRendering#266]
Hi,

I am trying to integrate your plugin into my own implementation of transfer function with custom opacity and color transfer functions. I am able to do it when I create those functions within your script hierarchy but I am unable to inherit TransferFunction class in my own scripts set up to create the transfer function and the texture. It looks like I must use your implementation of 'texture' variable. However, the variable defined in 'TransferFunction.cs' is private, and prevents me from generating a texture and use it along with your helper functions.

```
// Line 15 of TransferFunction.cs
private Texture2D texture = null;

```
I would like to avoid making changes to the plugin's source code, but having that variable defined as 'protected' will allow inheriting the class and create custom textures.

Are you open to making this change in your source code or accept a PR from a fork I create? Please let me know.

Thanks!

**Comment by mlavik1** [comment]
Hi!

That's a good point!
Rather than simply making it public, I'm considering doing some refactoring and maybe make some abstractions (an interface, etc.) for transfer functions. I also have some WIP stuff that needs to extend the transfer functions.
I'm hoping to find time to do this soon. I try to keep backwards compatibility in mind though (gradually deprecating things, to make sure projects using the plugin don't break when they upgrade, so it's a little bit tricky :sweat_smile: haha)

Thanks for the feedback!
For now I'd suggest that you simply make it public, or as a hack (if you for practical reasons want to avoid forking the repo) you could use [reflection](https://www.c-sharpcorner.com/blogs/setting-and-getting-private-variable-of-a-class-without-properties) to access the private variable.. that's quite hacky though :sweat_smile: 

But for now I'll keep it private, because if I make it public then it will be harder to refactor later (I'd need to deprecate it first and ensure backwards compatibility when rewriting the code, at least for a few months).

**Comment by mlavik1** [comment]
Ah wait, you suggested to make it "protected" and not "public". That should be fine! Thanks, I'll merge your PR! :)
