### ISSUE TITLE
DICOM support

### ISSUE THREAD

**Issue by MusoAga** [mlavik1/UnityVolumeRendering#4]
Very nice project. Thank you. I am working on a "DICOM to Mesh" project and found this repo here. I can already read and get values of DICOM. I already see you want to add DICOM Support.

What is in your mind to solve this problem?
What does the importer needs to know, to render the volume of the .dat? My goal is to convert the DICOM to the .dat file. Or would it be possible to use your importer directly with the .dcm files.

Awesome project and thank you for sharing!

**Comment by mlavik1** [comment]
Thank you very much! :)

Oh nice, hat sounds interesting!
Yes, I'm hoping to add DICOM support when I have more time. Though, I don't have any experience with DICOM yet, so I'll have to study the format first.

Hmm, good question!
You can either A: (as you said) export to raw format, or B: create your own importer class (that uses your own DICOM importing code.

**A) Export to raw format:**
This might be the easiest solution.
Simply export your data to a binary file "filename.raw" (use ".raw" instead of ".dat", since ".dat" assumes the file has a header).
I don't know how you store the dataset, but if it's inside a 3-dimensional array you could do something like this:
```
for(int x = 0; x < xDimension; x++)
   for(int y = 0; i y xDimension; y++)
       for(int z = 0; z < zDimension; z++)
           binaryWriter.Write(dataset[x,y,z]);
```
When importing the file, you need to enter
- X Dimension / Y Dimension / Z Dimension
- Data format (of each cell)
- leave "Bytes to skip" to be 0. Some raw formats (such as the sample files) have a header, and in this case we need to skip some bytes before reading the content.
![image](https://user-images.githubusercontent.com/6906872/72833479-3410f700-3c87-11ea-8a5d-a960161c7476.png)

If you open RawDatasetImporter.cs you can see how I import raw files (I read the content into a 1D array, that I copy to a 3D texture).

**B) Create your own DICOM importer**
NOTE: I have just done some changes that should make this more intuitive, so you should first pull the latest changes from master.
To create your own importer, you need to do the following:
1. Create a class that inherits from "DatasetImporterBase" and implements `public override VolumeDataset Import()`. The function should create a `VolumeDataset` instance, and set the following properties:
- _dimX_, _dimY_, _dimZ_ (the X/Y/Z dimension of the dataset)
- _data_ (an int array containing all the data values) - you need to cast the values to int
2. In `DatasetImporterEditorWindow.ImportDataset` in the "DICOM" switch case, remove the NotImplementedException and instead create an instance of your importer like this:
`importer = new DICOMImporter(fileToImport);`
(given that your importer class from (1) is called "DICOMImporter", and takes the file name as a parameter to the constructor)
After my last commit, the function now looks like this:
![image](https://user-images.githubusercontent.com/6906872/72837197-5eb27e00-3c8e-11ea-8f6a-3eaae186b0e2.png)

Hope this helped! 
And thanks for asking! This made me realise a few flaws that I have now corrected in my last two commits :)

**Comment by MusoAga** [comment]
Wow thanks for the great answer. İt helped a lot.

İ take a look into your commit. The Dicom files extensions are .dcm. And İ think a single dicom file will not be enough, to render a volume out of it. İ already start to read out the values of the dicom files and try to prepare the values so İ can use e. g. the marching cubes or your code. 

So İ think we will need these steps:

- read all dicom files from directory. İ use _fo-dicom_ in the asset store
- get tag values of every single dicom file. 
We will need the columns _(dimX)_, rows _(dimY)_ and the slice count, which is our depth _(dimZ)_. Actually the we need the columns and rows one time, to calculate the dimensions. 
- read out the pixel data of every single dicom file and calculate the hounsfield value, which will be our _data_. Currently İ am stucked here 😁

All these values are contained in a .dcm file and can get with its dicom tags. 

For calculating the pixel data other values also required, like pixel spacing. 

İ think with these values your algorithm should be happy. That ist what İ hope.

İ will give it a try and tell you about my progress 😊

**Comment by mlavik1** [comment]
Thanks a lot for sharing info about the DICOM format!
I think this will be useful for me later :) 
By the way, do you happen to know about any publically available DICOM datasets that could be good to use for testing this? 

For rendering I use marching cubes (3 different modes). I have described the implementation here: https://matiaslavik.wordpress.com/2020/01/19/volume-rendering-in-unity/
My implementation is quite basic though. The main (direct volume rendering) shader is only 42 lines (+ some extra functions).

**Comment by MusoAga** [comment]
İ know this sites. But İ do not really not knwo when a DİCOM file is good for this purpose. İ am sure, that there will be big difference, if its a CT, MR, US... Also there exists compressed and uncompresses files. Not every library, which reads dicoms, can handle this. For example the VTK lib can only read uncompressed dicom files. İ will try out. 

www.dicomlibrary.com
https://demo.softneta.com/md5/search.html

İ will read your blog. Unfortunately İ am not so good with shaders, but İ will try to understand 😁

**Comment by mlavik1** [comment]
Oh, I see. Thanks for the info, and for the links!
Volume/medical visualisation isn't really my field, so I don't know much about which file formats are used in which cases.

Oh, yes shaders can be a little hard at first when if you haven't worked a lot with it (since the whole rendering pipeline is a rather complicated subject), but once you know the basics and get some practice it's not that bad :grin: I find Unity really good for experimenting with shaders.

**Comment by MusoAga** [comment]
Hey mlavik1. After many tries I could read a DICOM Series and show the bones with your shader 😃 

I read and get the HU Values of the DICOM Series. There are also HU Values that has negative values, to handle the parts of the body, like lung or fat. (see [Wiki](https://en.wikipedia.org/wiki/Hounsfield_scale) ). 

I do not know if its specific to your shader or if its a general problem, but if the array contains a negative value a IndexOutOfBounds error occurs in HistogramTextureGenerator.cs line 15.

`values[dataset.data[iData]] += 1;`

I did not use the raw importer and read the files directly in code and just set the negative values to 1. 

Do you have an idea? Later I will post the code, how I solved it.

**Comment by mlavik1** [comment]
Hi @MusoAga.
Great work on importing the DICOM series! 

Oh, this is is `HistogramTextureGenerator.Generate2DHistogramTexture`, right? Looking at that function now I realise it's not very smart. I'll take a look at it after work today or tomorrow. It doesn't take negative data values into account, and it scales poorly with the data range (if the max value is really large it uses more time and memory than it should).

Until then, maybe you can try something like this:
![image](https://user-images.githubusercontent.com/6906872/73264575-6bc1f680-41d3-11ea-85e8-d8f27eaa148f.png)
I can't test it on this PC, but I think it should work. The main changes are:
`int numSamples = dataset.GetMaxDataValue() + 1 - dataset.GetMinDataValue();`
and
`int index = dataset.data[iData] - dataset.GetMinDataValue();`
`values[index] += 1;`
(inside the loop)

**Comment by MusoAga** [comment]
Hey @mlavik1 genius! I think it worked, now I can see the organs and other stuff.

Also set the index of:

`maxFreq = System.Math.Max(values[index], maxFreq);`

This is how it looks like now. It is not perfect, but for now I am happy with this.

![mesh](https://user-images.githubusercontent.com/12189192/73280756-45aa4f80-41ef-11ea-9c74-01be4d4dbb3a.jpg)
![mesh2](https://user-images.githubusercontent.com/12189192/73280757-4642e600-41ef-11ea-85d0-0f0fb7177532.jpg)

**Comment by MusoAga** [comment]
Like I said. I used [fo-dicom](https://assetstore.unity.com/packages/tools/integration/fo-dicom-60902) from the asset store. For the calculation of the HU Value we need the dimensions. 

```
DicomFile dicomFile = Dicom.DicomFile.Open(path);
DicomDataset dicomDataset = dicomFile.Dataset;

int columns = dicomDataSet.Get<int>(DicomTag.Columns);
int rows = dicomDataSet.Get<int>(DicomTag.Rows);
```

Row * Column is the dimension of a single slice. So it is still 2D. To get 3D we need the depth of the DICOM Serie. Here I am not sure how to calculate it. It is not the slice count, as I said before. Because there can be spaces between slices. The e.g. MRI or CT is not scanning continuously and can skip some parts of the body. But let us assume we have our depth.

So our dimension is:

```
int dim = rows * columns * depth;
int[] voxelData = new int[dim];
```

Now we need to fill the voxel with data. For this we need to extract the Pixel Data of single DICOM slice to calculate the HU Value. I will just copy the whole block.

```
private void InitPixelData()
{
    GrayscaleRenderOptions renderOpt = GrayscaleRenderOptions.FromDataset(_dicomDataSet);

    // Create PixelData object to represent pixel data in dataset
    DicomFile uncompressedClone = _dicomFile.Clone(DicomTransferSyntax.ExplicitVRLittleEndian);
    DicomPixelData pixel_data = DicomPixelData.Create(uncompressedClone.Dataset);
    // Pixel data interface implemented by various pixel format classes
    _pixelData = PixelDataFactory.Create(pixel_data, 0);

    _transformationLinear = renderOpt.VOILUTFunction.Equals("LINEAR");

    if (!_transformationLinear)
    {
        /**
            * LUT is for LookUpTable
            * Knows from renderOpt the Max and Min Pixel Values in the Stream
            * 
            * lowest_visible_value = window_center - window_width / 2
            * highest_visible_value = window_center + window_width / 2
            * 
            * Has the RescaleIntercept and RescaleSlope Values.
            * The rescale intercept and slope are applied to transform the pixel values of the image into 
            * values that are meaningful to the application. (e.g. hounsfield)
            * Rescale intercept and slope are a simple linear transform applied to 
            * the raw pixel data before applying the window width/center. 
            * 
            * When the transformation is not linear, then a LUT (lookup table) is applied.
            * */
        ModalityLUT lut = new ModalityLUT(renderOpt);

        /*
            * Render the pixel data after applying lut to the output array (allocated by user)
            * final_value = original_value * rescale_slope + rescale_intercept
            * */
        _pixelData.Render(lut, _hounsfieldPixelBuffer);
    }
}


public int GetHUValue(int row, int col)
{
    if(_transformationLinear)
    {
        int orgPixelValue = (int)_pixelData.GetPixel(row, col);

        if (_hasPaddingValue)
        {
            if (orgPixelValue == _pixelPaddingValue)
            {
                orgPixelValue = Int16.MinValue;
            }
        }

        int huValue = orgPixelValue * _rescaleSlope + _rescaleIntercept;

        return huValue;
    }
    else
    {
        int huIndex = row + (col * _rows);
        return _hounsfieldPixelBuffer[huIndex];
    }
}
```

Now we can set our voxel data.

```
public void InitDicomSlices()
{
    for (int x = 0; x < rows; x++)
    {
        for (int y = 0; y < columns; y++)
        {
            for (int z = 0; z < depth; z++)
            {
                int index = x + y * rows+ z * rows* columns;
                int hu = dicomDatas[z].GetHUValue(x, y);

                _voxels[index] = hu;
            }
        }
    }
}
```

How you store the dicom collection and handle the reading is up to you :) For now it works with your volume rendering. I also could use other marching cubes implementations with this value. Of course it could also be possible to use a 3D array if other codes take 3D array as input.

`int[,,] voxel = new int[row, col, depth];`

I do not know if this code works with every dicom data. For example this code here

`_pixelData = PixelDataFactory.Create(pixel_data, 0);`

Gets the PixelData of the first frame. If the dicom data contains many frames or is fragmented, I think this code will not work.

**Comment by mlavik1** [comment]
Nice work!
I'm happy to see other datasets than the saple datasets working in the project :) 

And thanks for sharing the code!
"fo-dicom" looks promising, so I will look into it and maybe create a branch with DICOM support (or merge it into master). However, I'm not entirely sure if I can re-distribute the fo-dicom source code in my repository since it uses "Microsoft Public License" (MS-PL).. Maybe it's OK if it is a Git submodule? I'm not an expert at this licenses, so I'll do some more reading first :sweat_smile:

**Comment by MusoAga** [comment]
No problem :) Unfortunately I just code it as a prototype. Thats why I could only show snippets. I am working on a nice solution right now. I can share it and you can decide if you want it :D 

I am not sure about the License, because the fo-dicom is available  in the asset store for free. Maybe then the license is not relevant. 

The version in github does not work really with Unity. In Visual Studio you can add the fo-dicom with the NuGet Manager, but unity removes the package again. There are also a Plugin for Unity to use the NuGet Manager. But it could not handle the fo-dicom. I do not know why, maybe I did it wrong. I didn't go into it any further. You can try again.

**Comment by mlavik1** [comment]
Oh, I see. What kind of project is it? (if I may ask. Just curious!  ).
Sure! If you don't mind :)

On second thought, I can just create a separate branch that uses the same license as fo-dicom. Then people can use this branch if they want DICOM support.
Right, I see. So you had to use the version from the asset store, right?
I can't re-distribute the asset store version (since it has a different license that does not allow it), but I'll give the github version a try!

**Comment by MusoAga** [comment]
Hehe nothing special just a bachelor's thesis 😁

Yes İ used the one from the asset store.

**Comment by mlavik1** [comment]
Of course!
I'm happy if my project can be useful to you 😄 

Good luck with your bachelor thesis!
I'll keep working on the project, so feel free to let me know if you encounter any issues or have any feature requests.

**Comment by MusoAga** [comment]
Hey @mlavik1 ! Thanks :) 

I have a question about the shader. Are the Min and Max Values in the VolumeDataset clamped or mapped to 0-1? I am talking about:

```
_MinVal("Min val", Range(0.0, 1.0)) = 0.0
_MaxVal("Max val", Range(0.0, 1.0)) = 1.0
```

So If I understand the shader: If I have values between `-1000` and `3000`, the `0` would represent `-1000` and `1` would represent `3000`. Is this right?

I am trying to implement the Window Center/Width Standard of DICOM. It is described [here](https://dicom.innolitics.com/ciods/ct-image/voi-lut/00281050)

Or should I just use the DirectVolumeRendering with your Transferfunctions for this purpose?

For example for: "showing the Skin transparent in blue color and the bones solid in grey".

Btw.: This is the new Plugin by VTK. I will check this out.

[VTK Plugin](https://assetstore.unity.com/packages/essentials/tutorial-projects/vtkunity-medicalviewer-162395#description)

**Comment by mlavik1** [comment]
Hi!
Yes, your understanding is right. The samples are normalised to values between 0 and 1.

if I get you right, what you want to do is set min/max value in the range -1000 to 3000, right?
I realise now that it's inconvenient to set this in the normalized range 0.0->1.0, so this is definitely something I should implement.
I'll make another GUI that allows you to do this.
In the meanwhile, you can use this temporary (work in progress) menu I made. 
Simply add this script to "Assets/Editor":
https://gist.githubusercontent.com/mlavik1/ce05c2ed817eee8ddaba80fb740bd441/raw/f048c00cd527f12bafc70022c8c4143745b18897/DataRangeEditorWindow.cs

Then open the "Data range menu"
![image](https://user-images.githubusercontent.com/6906872/74872648-ec50be80-535d-11ea-930c-4c23a74d3730.png)

And set your min/max values here.
![image](https://user-images.githubusercontent.com/6906872/74872619-d9d68500-535d-11ea-95d0-254ae8259cd2.png)

This looks best (and makes most sense) when using the "isosurface Rendering" mode.

If you want to do this from code instead, you can convert your int value to normalised float like this: `float min = (minInt - minDataVal) / (float)(maxDataVal - minDataVal);` (where minDataVal is -1000 and macDataVal is 3000, in your case)
And apply it to the material like this: `volobj.GetComponent<MeshRenderer>().sharedMaterial..SetFloat("_MinVal", min);`
I'll add some functionality to simplify this later.

Hope this helps!
I'll work on a proper solution, and merge it into master soon.
Again, thanks for the feedback!

**Comment by mlavik1** [comment]
Update: I noticed an issue with negative data values. You might want to merge in this commit (or just pull latest master) to make sure you can filter your data values properly: 00d1aa9
(there was a mistake in VolumeObjectFactory.cs that made negative data values not be normalised properly)

**Comment by mlavik1** [comment]
Hello again, @MusoAga!
Just writing to let you know that my first implementation of DICOM support has been merged into master. There are still some things left to do (correct scaling of axis, etc.), but the importer seems to work fine - at least on the datasets I used.
Thanks for all the help! (the info you shared about DICOM + the code you shared above).

**Comment by mlavik1** [comment]
Closing this issue, since there now is DICOM support. If there are any issues, feel free to re-open :)
