### ISSUE TITLE
Out of memory when import DICOM

### ISSUE THREAD

**Issue by csyhping** [mlavik1/UnityVolumeRendering#41]
Hi @mlavik1 ,thanks for your amazing work. When I tried to import my DICOM dataset with 576 .dcm files, it raises "Out of memory error" in [https://github.com/mlavik1/UnityVolumeRendering/blob/4a4d15f4f18cf3683b762b0cbc2013420a4c4bc2/Assets/Scripts/VolumeData/VolumeDataset.cs#L69](url), do you have any ideas why this happens? Thank you!

**Comment by mlavik1** [comment]
Thanks for the issue report!
It probably happened because your dataset is quite large and it ran out of memory while creating the 3D data texture, but looking at the code now I realise that it's wasting a lot of memory 😅 The data values are stored in a Color struct, which will use 4 times more memory that we really need.
I'll see if I can fix that!
You might still get an Out Of Memory exception in the histogram generation code though.. But as a fallback, it would be nice if the import still succeeds - just without transfer function support.

I'll start looking at this as soon as I have time 😄

**Comment by csyhping** [comment]
@mlavik1 , thanks for your reply. Besides, it seems currently the 3D model is built by rendering, is it possible to import mesh file (like .obj, .off, etc) directly so that we may manipulate on it? Thanks !

**Comment by mlavik1** [comment]
Since this project is focused on volume rendering (of 3D sampled data) there is no support for mesh files like OBJ and FBX.
If you want to load normal 3D meshes at runtime, I would recommend to use an importer library like Assimp. There seems to be a C# warapper for it called AssimpNet. And there are also some Unity wrappers on GitHub: https://github.com/ZohaibJaved/AssImpUnityWrapper/

**Comment by csyhping** [comment]
@mlavik1 Thanks for your reply, and thanks for your amazing work!

**Comment by mlavik1** [comment]
Thanks @csyhping ! 😄
