### ISSUE TITLE
Any plan to reorganize the code to fit the package manager?

### ISSUE THREAD

**Issue by sinloss** [mlavik1/UnityVolumeRendering#42]
Hi, great guys of this great project! Thank you all very much for this wonderful project!

And I'm wondering if there's any chance that the code could be reorganized to fit the **[Unity's Package Manager](https://docs.unity3d.com/Manual/Packages.html)**? It'll be more convenient to use, I think.

If it is allowed, I'm more than happy to do this work, which I've achieved locally. 

All the best!

**Comment by mlavik1** [comment]
Hi!
That's a good idea!
Thanks for offering to do that 😃 Since the project is MIT licensed everyone is free to redistribute it, but if I understand Unity's submission guidelines correctly I think maybe the submitter has to be the main developer or something?
https://unity3d.com/asset-store/sell-assets/submission-guidelines (see 1.1.1.b).
If so, I can probably try to get it done some time next week. I'll need to do some changes to the license files first though (Unity seems to have some specific rules about how to acknowledge open source libraries that you use in the project).

**Comment by sinloss** [comment]
That'll be very great!

**Comment by mlavik1** [comment]
Waiting for approval from Unity now :)
