### ISSUE TITLE
Importing NRRD with SimpleITK

### ISSUE THREAD

**Issue by Elektropepi** [mlavik1/UnityVolumeRendering#53]
We implemented a NRRDImporter with SimpleITK. It's pretty performant (~300ms to read a 30MB compressed .nrrd file and assigning all necessary variables of the VolumeDataset).

SimpleITK could also be used to read DICOM instead of openDICOM (using the same logic of our NRRDImporter) and more files since it's a versatile library.

Would you be interested in a Pull Request for the NRRDImporter since it'd introduce ~100MB SimpleITK .dlls from [here](https://sourceforge.net/projects/simpleitk/files/SimpleITK/1.2.4/CSharp/)?

**Comment by mlavik1** [comment]
That sounds really nice!
I wasn't familiar with SimpleITK, but that could probably be a good replacement for openDICOM.

However, I see one issue: Since this project is aiming to be cross platform, we'll need to add the library files (.dll/.so) for all platforms we want to support. That will take up a lot of space, and would probably be better to store somewhere else (and download on demand).
I think maybe a good solution could be to merge your c# code into this repository, and create a "USE_ITK" preprocessor definition that you can enable to support NRRD (or use SimpleITK for DICOM) + a script that downloads the DLLs. Then it should be Ok to only support Windows/Linux at first I think, since you'll still be able to use the project on other platforms without SimpleITK.

Is your fork open somewhere, so I can see how many changes there are first?

**Comment by mlavik1** [comment]
So I decided to take a look at SimpleITK now, and it seems great! Not only does it allow us to import NRRD datasets, but it also supports DICOM with JPEG2000. (so thanks a lot for the suggestion!)

**My suggestion:**
- I will write a SimpleITKImporter class, that only compiles if "USE_SIMPLEITK" is #defined.
- In a settings menu (or in a popup on first time use), the user can enable using SimpleITK.
- This will auto-download the binaries fromm SourceForge, and enable "USE_SIMPLEITK" preprocessor definition [like this](https://docs.unity3d.com/Manual/CustomScriptingSymbols.html), which will enable the custom SimpleITK-based importer.
- SimpleITKImporter will be used instead of the current DICOMImporter.

This way, users can choose to use SimpleITK on all supported platforms, and use the existing OpenDICOM.Net based importer where it's not supported.

It's importing fine so far btw:
![bilde](https://user-images.githubusercontent.com/6906872/160460847-773a0e08-c6df-4107-bc7e-2426579980d8.png)

**Comment by mlavik1** [comment]
Fixed by #95
