### ISSUE TITLE
Can't load DICOM files

### ISSUE THREAD

**Issue by IngGabriela** [mlavik1/UnityVolumeRendering#72]
I have this error when I try to import DICOM files
![image](https://user-images.githubusercontent.com/93385314/142415534-39538601-6caa-41f0-b490-e8a0127fa0b5.png)
I think I am pretty dumb but I really don't know what's the problem

**Comment by vahpy** [comment]
Nah, this is a good question actually. I have faced this before. I guess you have copied the whole files and folders from "Assets" to a folder like "VolumeRendering" as a package to organise files in your project. This is the reason you get this error. You can solve it by copying/pasting the StreamingAssets to the root Assets folder. I will look at it today.
Also, in case you might have downloaded the package from AssetStore, I recommend this repository instead, because that package is outdated and it's more likely to get errors. Or @mlavik1 could you update the package on AssetStore?

**Comment by mlavik1** [comment]
Hi, @IngGabriela I just replied to you in #68 .

And @vahpy : Yes, I'll do that 👍 I'll see if I can do it on Sunday, or maybe sometime next week, since I need to find a better fix for this issue first.

**Comment by IngGabriela** [comment]
@mlavik1 Sorry, I hadn't seen
